Repository react-native-community/cli, pull requests merged in 2022-12, with the labels that each got.

#1777 chore: update release-drafter.yml
  .github/release-drafter.yml
Labels: infra

#1776 chore: run release drafter on pull request open
  .github/workflows/release-drafter.yml
Labels: infra

#1577 feat: add --binary-path to run-ios and run-android to enable installing pre-build binaries
  docs/commands.md
  packages/cli-platform-android/src/commands/runAndroid/index.ts
  packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
  packages/cli-platform-android/src/commands/runAndroid/tryInstallAppOnDevice.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
Labels: docs, feature

#1782 feat: add condition for min node version
  packages/cli-doctor/src/index.ts
  packages/cli/src/bin.ts
Labels: feature

#1779 feat: run app on iOS and Android with a hotkey
  packages/cli-plugin-metro/package.json
  packages/cli-plugin-metro/src/commands/start/watchMode.ts
Labels: feature

#1781 feat: add support for running app on all booted devices and simulators
  packages/cli-platform-ios/src/commands/runIOS/index.ts
Labels: docs, feature

#1783 chore: add `yarn lint` on pre-commit with husky
  .husky/pre-commit
  package.json
  yarn.lock
Labels: infra

#1785 fix: when used with option --port and --deviceId not working on run-android
  packages/cli-platform-android/src/commands/runAndroid/index.ts
Labels: bugfix
