Repository react-native-community/cli, pull requests merged in 2023-09, with the labels that each got.

#2055 breaking: Delete source for cli-plugin-metro, remove from builtin commands
  CONTRIBUTING.md
  docs/commands.md
  packages/cli-doctor/tsconfig.json
  packages/cli-platform-android/tsconfig.json
  packages/cli-plugin-metro/CHANGELOG.md
  packages/cli-plugin-metro/README.md
  packages/cli-plugin-metro/package.json
  packages/cli-plugin-metro/src/commands/bundle/__mocks__/sign.js
  packages/cli-plugin-metro/src/commands/bundle/__tests__/filterPlatformAssetScales-test.ts
  packages/cli-plugin-metro/src/commands/bundle/__tests__/getAssetDestPathAndroid-test.ts
  packages/cli-plugin-metro/src/commands/bundle/__tests__/getAssetDestPathIOS-test.ts
  packages/cli-plugin-metro/src/commands/bundle/assetCatalogIOS.ts
  packages/cli-plugin-metro/src/commands/bundle/assetPathUtils.ts
  packages/cli-plugin-metro/src/commands/bundle/buildBundle.ts
  packages/cli-plugin-metro/src/commands/bundle/bundle.ts
  packages/cli-plugin-metro/src/commands/bundle/bundleCommandLineArgs.ts
  packages/cli-plugin-metro/src/commands/bundle/filterPlatformAssetScales.ts
  packages/cli-plugin-metro/src/commands/bundle/getAssetDestPathAndroid.ts
  packages/cli-plugin-metro/src/commands/bundle/getAssetDestPathIOS.ts
  packages/cli-plugin-metro/src/commands/bundle/index.ts
  packages/cli-plugin-metro/src/commands/bundle/ramBundle.ts
  packages/cli-plugin-metro/src/commands/bundle/saveAssets.ts
  packages/cli-plugin-metro/src/commands/index.ts
  packages/cli-plugin-metro/src/commands/start/index.ts
  packages/cli-plugin-metro/src/commands/start/runServer.ts
  packages/cli-plugin-metro/src/commands/start/watchMode.ts
  packages/cli-plugin-metro/src/index.ts
  packages/cli-plugin-metro/src/tools/KeyPressHandler.ts
  packages/cli-plugin-metro/src/tools/loadMetroConfig.ts
  packages/cli-plugin-metro/src/tools/metroPlatformResolver.ts
  packages/cli-plugin-metro/tsconfig.json
  packages/cli-plugin-metro/types/@react-native/metro-config/index.d.ts
  packages/cli/src/commands/index.ts
  packages/cli/tsconfig.json
  scripts/helpers.js
  yarn.lock
Labels: docs

#2062 fix: get only tasks for passed type
  packages/cli-platform-android/src/commands/runAndroid/listAndroidTasks.ts
Labels: bugfix

#2073 feat: add Bun to `init` command
  docs/commands.md
  packages/cli-clean/src/clean.ts
  packages/cli-doctor/src/tools/checkInstallation.ts
  packages/cli-doctor/src/tools/versionRanges.ts
  packages/cli-doctor/src/types.ts
  packages/cli/src/commands/init/__tests__/template.test.ts
  packages/cli/src/commands/init/index.ts
  packages/cli/src/commands/init/init.ts
  packages/cli/src/commands/init/template.ts
  packages/cli/src/tools/__tests__/packageManager-test.ts
  packages/cli/src/tools/bun.ts
  packages/cli/src/tools/npm.ts
  packages/cli/src/tools/packageManager.ts
  yarn.lock
Labels: docs, feature

#2071 fix: improve providing project name in `init` command
  __e2e__/__snapshots__/default.test.ts.snap
  __e2e__/init.test.ts
  packages/cli-clean/src/__tests__/clean.test.ts
  packages/cli-platform-android/src/commands/runAndroid/__tests__/listAndroidTasks.test.ts
  packages/cli/src/commands/init/index.ts
  packages/cli/src/commands/init/init.ts
Labels: bugfix

#2072 feat: upgrade Android Studio version when installing on Windows
  packages/cli-doctor/src/tools/healthchecks/androidStudio.ts
Labels: feature

#2049 feat(doctor): adjust healthchecks based on where command was ran
  packages/cli-doctor/package.json
  packages/cli-doctor/src/tools/healthchecks/index.ts
Labels: feature, bugfix

#2078 refactor(iOS): remove unintended flags from build-ios
  __e2e__/__snapshots__/config.test.ts.snap
  packages/cli-platform-ios/README.md
  packages/cli-platform-ios/src/commands/buildIOS/buildOptions.ts
  packages/cli-platform-ios/src/commands/buildIOS/buildProject.ts
  packages/cli-platform-ios/src/commands/buildIOS/getConfiguration.ts
  packages/cli-platform-ios/src/commands/buildIOS/getXcodeProjectAndDir.ts
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-platform-ios/src/tools/getBuildConfigurationFromXcScheme.ts
  packages/cli-platform-ios/src/tools/getConfigurationScheme.ts
  packages/cli-platform-ios/src/tools/selectFromInteractiveMode.ts
Labels: docs

#2077 refactor: move pods installation from `init` to ios-specific commands
  __e2e__/config.test.ts
  __e2e__/init.test.ts
  __e2e__/root.test.ts
  docs/commands.md
  docs/platforms.md
  packages/cli-config/src/__tests__/__snapshots__/index-test.ts.snap
  packages/cli-config/src/__tests__/index-test.ts
  packages/cli-config/src/schema.ts
  packages/cli-doctor/package.json
  packages/cli-doctor/src/index.ts
  packages/cli-doctor/src/tools/healthchecks/cocoaPods.ts
  packages/cli-platform-ios/README.md
  packages/cli-platform-ios/src/__tests__/pods.test.ts
  packages/cli-platform-ios/src/commands/buildIOS/buildOptions.ts
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-platform-ios/src/config/index.ts
  packages/cli-platform-ios/src/index.ts
  packages/cli-platform-ios/src/tools/installPods.ts
  packages/cli-platform-ios/src/tools/pods.ts
  packages/cli-platform-ios/src/tools/runBundleInstall.ts
  packages/cli-tools/package.json
  packages/cli-tools/src/cacheManager.ts
  packages/cli-tools/src/index.ts
  packages/cli-tools/src/releaseChecker/getLatestRelease.ts
  packages/cli-tools/src/releaseChecker/printNewRelease.ts
  packages/cli-tools/src/runSudo.ts
  packages/cli-types/src/ios.ts
  packages/cli/src/commands/init/index.ts
  packages/cli/src/commands/init/init.ts
Labels: docs

#2082 fix: add missing `--force-pods` flag for `run-ios` and `build-ios`
  packages/cli-platform-ios/src/commands/buildIOS/buildOptions.ts
Labels: bugfix

#2086 fix(iOS): restore simulator, device, and UDID args on `run-ios` command
  packages/cli-platform-ios/src/commands/runIOS/index.ts
Labels: bugfix

#2089 fix: Creating cache for scoped packages
  packages/cli-tools/src/cacheManager.ts
Labels: bugfix
