Repository react-native-community/cli, pull requests merged in 2023-04, with the labels that each got.

#1897 feat: add `newArchEnabled` and `hermesEnabled` to `info` command
  packages/cli-doctor/package.json
  packages/cli-doctor/src/commands/info.ts
  yarn.lock
Labels: feature

#1904 fix: change permission in `launchPackager.command` when building packages
  scripts/build.js
Labels: bugfix

#1913 feat: change default `taskPrefix` in `build-android` command
  packages/cli-platform-android/src/commands/buildAndroid/index.ts
  packages/cli-platform-android/src/commands/runAndroid/getTaskNames.ts
Labels: feature, bugfix

#1916 fix: add missing arguments to `adb shell` in `run-android` command
  packages/cli-platform-android/src/commands/runAndroid/tryLaunchAppOnDevice.ts
Labels: bugfix

#1915 fix: delete `com.` prefix in package name
  packages/cli/src/commands/init/__tests__/editTemplate.test.ts
  packages/cli/src/commands/init/editTemplate.ts
Labels: bugfix

#1909 fix: str.replace not a function issue
  packages/cli-platform-ios/src/tools/getProjectInfo.ts
  packages/cli-tools/src/errors.ts
Labels: bugfix
