Repository react-native-community/cli, pull requests merged in 2023-10, with the labels that each got.

#2097 fix: add missing shebang to `launchPackager.command`
  packages/cli-tools/src/launchPackager.command
Labels: bugfix

#2118 Add AndroidTV to platforms.md docs
  docs/platforms.md
Labels: docs

#2112 fix: skip pods installation when it's already installed
  packages/cli-platform-ios/src/tools/pods.ts
Labels: bugfix

#2113 fix(android): properly handle errors
  packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
Labels: bugfix

#2111 fix: remove hardcoded path to iOS folder
  packages/cli-platform-ios/src/tools/installPods.ts
  packages/cli-platform-ios/src/tools/pods.ts
Labels: bugfix

#2122 fix: install pods on ios-commands with New Arch
  packages/cli-doctor/src/commands/info.ts
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-platform-ios/src/index.ts
  packages/cli-platform-ios/src/tools/getArchitecture.ts
  packages/cli-platform-ios/src/tools/installPods.ts
  packages/cli-platform-ios/src/tools/pods.ts
Labels: bugfix

#2103 fix: delete useless mocking in e2e tests
  __e2e__/init.test.ts
Labels: bugfix

#2130 chore: upgrade typescript & eslint
  jest/helpers.ts
  package.json
  packages/cli-debugger-ui/src/ui/index.js
  packages/cli-doctor/src/commands/doctor.ts
  packages/cli-doctor/src/commands/info.ts
  packages/cli-doctor/src/tools/healthchecks/__tests__/androidSDK.test.ts
  packages/cli-doctor/src/tools/healthchecks/__tests__/androidStudio.test.ts
  packages/cli-doctor/src/tools/healthchecks/__tests__/jdk.test.ts
  packages/cli-doctor/src/tools/healthchecks/__tests__/watchman.test.ts
  packages/cli-doctor/src/tools/windows/__tests__/androidWinHelpers.test.ts
  packages/cli-hermes/src/profileHermes/downloadProfile.ts
  packages/cli-hermes/src/profileHermes/index.ts
  packages/cli-platform-android/src/commands/runAndroid/__tests__/runOnAllDevices.test.ts
  packages/cli-platform-android/src/config/extractComponentDescriptors.ts
  packages/cli-platform-android/src/config/getAndroidProject.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-platform-ios/src/config/__tests__/native_modules.test.ts
  packages/cli-server-api/src/websocket/createEventsSocketEndpoint.ts
  packages/cli-tools/src/launchEditor.ts
  packages/cli-types/src/index.ts
  packages/cli/src/commands/init/editTemplate.ts
  yarn.lock
Labels: infra

#2121 fix: get scheme from `xcodeProject` name
  packages/cli-platform-ios/src/commands/buildIOS/getConfiguration.ts
  packages/cli-platform-ios/src/tools/__tests__/checkIfConfigurationExists.test.ts
  packages/cli-platform-ios/src/tools/checkIfConfigurationExists.ts
  packages/cli-platform-ios/src/tools/getBuildConfigurationFromXcScheme.ts
  packages/cli-platform-ios/src/tools/getInfo.ts
  packages/cli-platform-ios/src/tools/prompts.ts
  packages/cli-platform-ios/src/tools/selectFromInteractiveMode.ts
  packages/cli-platform-ios/src/types.ts
Labels: bugfix

#2133 fix: fallback first to `yarn` when `bun` not available
  packages/cli/src/tools/packageManager.ts
Labels: bugfix

#2128 fix: do not ask for port change when `--no-packager` provided
  packages/cli-platform-android/src/commands/runAndroid/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-tools/src/findDevServerPort.ts
  packages/cli-tools/src/handlePortUnavailable.ts
  packages/cli-tools/src/index.ts
Labels: bugfix

#2141 chore: replace `rimraf` package with `fs` calls
  __e2e__/config.test.ts
  __e2e__/default.test.ts
  __e2e__/init.test.ts
  __e2e__/root.test.ts
  __e2e__/unknown.test.ts
  jest/helpers.ts
  package.json
  packages/cli-config/src/__tests__/findDependencies-test.ts
  packages/cli-config/src/__tests__/index-test.ts
  packages/cli-doctor/src/tools/healthchecks/__tests__/androidSDK.test.ts
  packages/cli-platform-ios/src/__tests__/pods.test.ts
  packages/cli-tools/src/__tests__/findProjectRoot-test.ts
  packages/cli/src/tools/__tests__/copyFiles.test.ts
  yarn.lock
Labels: bugfix

#2138 feat: handle better canceling prompts
  packages/cli-clean/package.json
  packages/cli-clean/src/clean.ts
  packages/cli-doctor/package.json
  packages/cli-platform-android/src/commands/runAndroid/__tests__/listAndroidTasks.test.ts
  packages/cli-platform-android/src/commands/runAndroid/listAndroidDevices.ts
  packages/cli-platform-android/src/commands/runAndroid/listAndroidTasks.ts
  packages/cli-platform-android/src/commands/runAndroid/listAndroidUsers.ts
  packages/cli-platform-ios/src/commands/logIOS/index.ts
  packages/cli-platform-ios/src/tools/prompts.ts
  packages/cli-tools/src/prompt.ts
  packages/cli/src/commands/init/init.ts
Labels: feature

#2140 fix: add missing dependency
  package.json
  yarn.lock
Labels: bugfix

#2142 fix: remove eslint warnings
  .eslintrc.js
  packages/cli-clean/src/__tests__/clean.test.ts
Labels: bugfix

#2139 feat(docs): update section related to updating CLI
  README.md
Labels: docs, feature, bugfix

#2144 perf: remove Gradle task check on run-android
  packages/cli-platform-android/README.md
  packages/cli-platform-android/src/commands/buildAndroid/index.ts
  packages/cli-platform-android/src/commands/runAndroid/getTaskNames.ts
  packages/cli-platform-android/src/commands/runAndroid/index.ts
  packages/cli-platform-android/src/commands/runAndroid/listAndroidTasks.ts
  packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
Labels: docs

#2088 feat: create git repository in `init` command
  __e2e__/init.test.ts
  packages/cli/src/commands/init/createGitRepository.ts
  packages/cli/src/commands/init/init.ts
Labels: feature

#2102 fix(ios): check if there are any available simulators or physical devices
  packages/cli-platform-ios/src/commands/logIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
Labels: bugfix

#2116 feat: opt-in pod install with ios commands
  __e2e__/__snapshots__/config.test.ts.snap
  __e2e__/init.test.ts
  docs/projects.md
  packages/cli-config/src/schema.ts
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-platform-ios/src/config/__tests__/getProjectConfig.test.ts
  packages/cli-platform-ios/src/config/index.ts
  packages/cli-platform-ios/src/tools/installPods.ts
  packages/cli-types/src/ios.ts
  packages/cli/package.json
  packages/cli/src/commands/init/init.ts
Labels: docs, feature

#2135 fix: force users to use `nodeLinker: node-modules` when installing template packages
  packages/cli/src/commands/init/template.ts
  packages/cli/src/tools/packageManager.ts
Labels: feature
