Repository react-native-community/cli, pull requests merged in 2023-03, with the labels that each got.

#1849 Add `unstable_reactLegacyComponent` to `cli-platform-android`
  docs/projects.md
  packages/cli-config/src/schema.ts
  packages/cli-platform-android/native_modules.gradle
  packages/cli-platform-android/src/config/__tests__/__snapshots__/getProjectConfig.test.ts.snap
  packages/cli-platform-android/src/config/index.ts
  packages/cli-types/src/android.ts
Labels: docs

#1859 Add the `unstable_reactLegacyComponentNames` to iOS project config
  docs/projects.md
  packages/cli-config/src/schema.ts
Labels: docs, feature

#1854 fix: doctor for 0.72 Ruby changes
  packages/cli-doctor/src/commands/doctor.ts
  packages/cli-doctor/src/tools/envinfo.ts
  packages/cli-doctor/src/tools/healthchecks/__tests__/ruby.test.ts
  packages/cli-doctor/src/tools/healthchecks/common.ts
  packages/cli-doctor/src/tools/healthchecks/ruby.ts
  packages/cli-doctor/src/tools/versionRanges.ts
  packages/cli-doctor/src/types.ts
Labels: bugfix

#1868 fix: tests
  packages/cli-doctor/src/tools/healthchecks/ruby.ts
  packages/cli-doctor/src/tools/healthchecks/xcodeEnv.ts
Labels: bugfix

#1851 fix: remove installing `cocoapods` with `brew`
  packages/cli-doctor/src/tools/healthchecks/cocoaPods.ts
  packages/cli-doctor/src/tools/installPods.ts
Labels: bugfix

#1863 fix: correctly list ios devices and simulators
  __e2e__/__snapshots__/config.test.ts.snap
  docs/commands.md
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/listIOSDevices.ts
  packages/cli-platform-ios/src/tools/__tests__/findMatchingSimulator.test.ts
  packages/cli-platform-ios/src/tools/__tests__/getDevices.test.ts
  packages/cli-platform-ios/src/tools/__tests__/listIOSDevices.test.ts
  packages/cli-platform-ios/src/tools/__tests__/parseIOSDevicesList.test.ts
  packages/cli-platform-ios/src/tools/__tests__/parseXctraceIOSDevicesList.test.ts
  packages/cli-platform-ios/src/tools/findMatchingSimulator.ts
  packages/cli-platform-ios/src/tools/getDevices.ts
  packages/cli-platform-ios/src/tools/listIOSDevices.ts
  packages/cli-platform-ios/src/tools/parseIOSDevicesList.ts
  packages/cli-platform-ios/src/tools/parseXctraceIOSDevicesList.ts
  packages/cli-platform-ios/src/tools/prompts.ts
Labels: docs, bugfix

#1862 feat: Set "react-native" condition when using Package Exports
  packages/cli-plugin-metro/src/tools/loadMetroConfig.ts
Labels: feature

#1878 fix: Getting rid of stack trace for `Installing Bundler` errors
  packages/cli-doctor/src/tools/runBundleInstall.ts
Labels: bugfix

#1871 docs: add missing `README.md` for all packages.
  docs/commands.md
  packages/cli-clean/README.md
  packages/cli-config/README.md
  packages/cli-doctor/README.md
  packages/cli-hermes/README.md
  packages/cli-platform-android/README.md
  packages/cli-platform-ios/README.md
  packages/cli-plugin-metro/README.md
Labels: docs

#1867 docs: update link to latest main Podfile
  docs/autolinking.md
Labels: docs

#1870 feat: add deeplinks to our documentation
  __e2e__/__snapshots__/config.test.ts.snap
  babel.config.js
  package.json
  packages/cli-config/src/__tests__/__snapshots__/index-test.ts.snap
  packages/cli-config/src/__tests__/index-test.ts
  packages/cli-config/src/loadConfig.ts
  packages/cli-doctor/src/commands/info.ts
  packages/cli-doctor/src/tools/healthchecks/androidSDK.ts
  packages/cli-doctor/src/tools/healthchecks/androidStudio.ts
  packages/cli-doctor/src/tools/healthchecks/jdk.ts
  packages/cli-doctor/src/tools/healthchecks/ruby.ts
  packages/cli-doctor/src/tools/installPods.ts
  packages/cli-doctor/src/tools/runBundleInstall.ts
  packages/cli-platform-android/src/commands/runAndroid/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-plugin-metro/src/commands/start/runServer.ts
  packages/cli-tools/src/__tests__/doclink.test.ts
  packages/cli-tools/src/doclink.ts
  packages/cli-tools/src/errors.ts
  packages/cli-tools/src/index.ts
  packages/cli-tools/src/releaseChecker/getLatestRelease.ts
  packages/cli-tools/src/releaseChecker/index.ts
  packages/cli-tools/src/releaseChecker/printNewRelease.ts
  packages/cli-types/src/index.ts
  yarn.lock
Labels: feature

#1885 feat : Add adb devices and reverse proxy test in cli-doctor
  packages/cli-doctor/package.json
  packages/cli-doctor/src/tools/healthchecks/adb.ts
  packages/cli-doctor/src/tools/healthchecks/index.ts
  packages/cli-doctor/tsconfig.json
  packages/cli-platform-android/src/commands/runAndroid/index.ts
  packages/cli-platform-android/src/index.ts
  packages/cli-tools/src/doclink.ts
Labels: feature

#1886 [10.x] chore(deps): Metro to 0.73.9 (Windows/Linux watcher fixes)
  package.json
  packages/cli-plugin-metro/package.json
  yarn.lock
Labels: infra

#1812 fix: Replace calling internal React Native scripts for launching Metro with CLI's script
  .gitignore
  packages/cli-platform-android/package.json
  packages/cli-platform-android/src/commands/buildAndroid/index.ts
  packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts
  packages/cli-plugin-metro/launchPackager.bat
  packages/cli-plugin-metro/launchPackager.sh
Labels: bugfix

#1887 fix: link inside `printRunDoctorTip.ts`
  packages/cli-tools/src/printRunDoctorTip.ts
Labels: bugfix

#1890 fix: `log-ios` command
  __e2e__/__snapshots__/config.test.ts.snap
  packages/cli-platform-ios/README.md
  packages/cli-platform-ios/src/commands/logIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-platform-ios/src/tools/getSimulators.ts
Labels: docs, bugfix

#1895 fix: replace `launchPackager.sh` with `launchPackager.command`
  packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts
  packages/cli-plugin-metro/launchPackager.command
Labels: bugfix
