Repository react-native-community/cli, pull requests merged in 2023-06, with the labels that each got.

#1946 fix: `--verbose` option not working for `run-ios`
  packages/cli/src/index.ts
Labels: bugfix

#1953 fix: always add `--verbose` to the command
  __e2e__/__snapshots__/default.test.ts.snap
  packages/cli/src/index.ts
Labels: bugfix

#1954 chore: use slash for windows paths
  __e2e__/init.test.ts
Labels: bugfix

#1962 fix: add logger to doctor unhandled errors
  packages/cli-doctor/src/commands/doctor.ts
  packages/cli-doctor/src/tools/runAutomaticFix.ts
Labels: bugfix

#1975 fix: remove `@ts-ignore` in `cli-plugin-metro`
  packages/cli-plugin-metro/src/commands/bundle/buildBundle.ts
  packages/cli-plugin-metro/src/commands/bundle/bundleCommandLineArgs.ts
  packages/cli-plugin-metro/src/commands/start/runServer.ts
Labels: bugfix

#1833 download correct sourceMap for dev/prod profiles, add warning for Expo Dev menu profiles
  packages/cli-hermes/src/profileHermes/downloadProfile.ts
  packages/cli-hermes/src/profileHermes/metroBundleOptions.ts
  packages/cli-hermes/src/profileHermes/sourcemapUtils.ts
Labels: stale

#1974 docs: replace `master` with `main`
  packages/cli-clean/package.json
  packages/cli-config/package.json
  packages/cli-debugger-ui/package.json
  packages/cli-doctor/package.json
  packages/cli-hermes/package.json
  packages/cli-platform-android/package.json
  packages/cli-platform-ios/native_modules.rb
  packages/cli-platform-ios/package.json
  packages/cli-platform-ios/src/config/__tests__/__snapshots__/findPodfilePath.test.ts.snap
  packages/cli-platform-ios/src/config/findPodfilePath.ts
  packages/cli-plugin-metro/README.md
  packages/cli-plugin-metro/package.json
  packages/cli-server-api/package.json
  packages/cli-tools/package.json
  packages/cli-types/package.json
  packages/cli/package.json
  packages/cli/src/commands/init/template.ts
Labels: docs

#1968 fix: remove useless check in `upgrade` command
  packages/cli-tools/src/releaseChecker/getLatestRelease.ts
Labels: bugfix

#1990 feat: Add alternative base config check to loadMetroConfig (11.x)
  packages/cli-plugin-metro/src/tools/loadMetroConfig.ts
Labels: feature

#1882 fix: doclinks should not select a default platform
  packages/cli-doctor/src/tools/healthchecks/adb.ts
  packages/cli-doctor/src/tools/healthchecks/androidSDK.ts
  packages/cli-doctor/src/tools/healthchecks/androidStudio.ts
  packages/cli-doctor/src/tools/healthchecks/jdk.ts
  packages/cli-doctor/src/tools/healthchecks/ruby.ts
  packages/cli-doctor/src/tools/installPods.ts
  packages/cli-doctor/src/tools/runBundleInstall.ts
  packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
  packages/cli-tools/src/__tests__/doclink.test.ts
  packages/cli-tools/src/doclink.ts
  packages/cli-tools/src/releaseChecker/printNewRelease.ts
Labels: bugfix

#1992 [11.x] chore: Update Metro to 0.76.7
  package.json
  packages/cli-plugin-metro/package.json
  yarn.lock
Labels: infra
