Repository react-native-community/cli, pull requests merged in 2023-01, with the labels that each got.

#1791 docs: update readme with version 10.0.0
  README.md
Labels: docs

#1795 fix: add missing activeArchOnly when using runOnSpecificDevice
  packages/cli-platform-android/src/commands/runAndroid/index.ts
Labels: bugfix

#1794 fix: e2e tests snapshot
  __e2e__/__snapshots__/config.test.ts.snap
Labels: bugfix

#1798 fix: use variant arg in build-android command
  docs/commands.md
  packages/cli-platform-android/src/commands/buildAndroid/index.ts
  packages/cli-platform-android/src/commands/runAndroid/getTaskNames.ts
  packages/cli-platform-android/src/commands/runAndroid/listAndroidDevices.ts
  packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
  packages/cli-platform-android/src/commands/runAndroid/toPascalCase.ts
Labels: docs, bugfix

#1802 fix: correctly exec launchEmulator when no port param is passed
  packages/cli-platform-android/src/commands/runAndroid/tryLaunchEmulator.ts
Labels: bugfix

#1806 fix: passing simulator via name
  packages/cli-platform-ios/src/commands/runIOS/index.ts
Labels: bugfix

#1744 feat: build-ios command
  docs/commands.md
  packages/cli-platform-ios/src/commands/buildIOS/buildProject.ts
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
  packages/cli-platform-ios/src/commands/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/listIOSDevices.ts
  packages/cli-platform-ios/src/tools/__tests__/findMatchingSimulator.test.ts
  packages/cli-platform-ios/src/tools/__tests__/getDevices.test.ts
  packages/cli-platform-ios/src/tools/__tests__/parseIOSDevicesList.test.ts
  packages/cli-platform-ios/src/tools/__tests__/parseXctraceIOSDevicesList.test.ts
  packages/cli-platform-ios/src/tools/findMatchingSimulator.ts
  packages/cli-platform-ios/src/tools/getDestinationSimulator.ts
  packages/cli-platform-ios/src/tools/getDevices.ts
  packages/cli-platform-ios/src/tools/parseIOSDevicesList.ts
  packages/cli-platform-ios/src/tools/parseXctraceIOSDevicesList.ts
Labels: docs, feature

#1810 feat: check if configuration for iOS project exists
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-platform-ios/src/tools/__tests__/checkIfConfigurationExists.test.ts
  packages/cli-platform-ios/src/tools/checkIfConfigurationExists.ts
  packages/cli-platform-ios/src/tools/getProjectInfo.ts
  packages/cli-platform-ios/src/types.ts
Labels: feature

#1773 feat: read build configuration from scheme file
  packages/cli-platform-ios/package.json
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-platform-ios/src/tools/getBuildConfigurationFromXcScheme.ts
  packages/cli-platform-ios/src/tools/getConfigurationScheme.ts
  yarn.lock
Labels: feature

#1808 feat: allow initialising project with custom package name with `init --package-name`
  docs/commands.md
  packages/cli/src/commands/init/__fixtures__/editTemplate/android/com/placeholdername/MainActivity.java
  packages/cli/src/commands/init/__fixtures__/editTemplate/ios/PlaceholderName/project.pbxproj
  packages/cli/src/commands/init/__tests__/__snapshots__/editTemplate.test.ts.snap
  packages/cli/src/commands/init/__tests__/editTemplate.test.ts
  packages/cli/src/commands/init/editTemplate.ts
  packages/cli/src/commands/init/index.ts
  packages/cli/src/commands/init/init.ts
Labels: docs, feature
