Repository react-native-community/cli, pull requests merged in 2023-05, with the labels that each got.

#1926 docs: update react-native Podfile template link
  docs/autolinking.md
Labels: docs

#1933 fix: trim whitespace in `parseTasksFromGradleFile` on Windows
  packages/cli-platform-android/src/commands/runAndroid/listAndroidTasks.ts
Labels: bugfix

#1869 feat: added --user flag to run-android command
  docs/commands.md
  packages/cli-platform-android/README.md
  packages/cli-platform-android/src/commands/runAndroid/__tests__/checkUsers.test.ts
  packages/cli-platform-android/src/commands/runAndroid/getTaskNames.ts
  packages/cli-platform-android/src/commands/runAndroid/index.ts
  packages/cli-platform-android/src/commands/runAndroid/listAndroidUsers.ts
  packages/cli-platform-android/src/commands/runAndroid/tryInstallAppOnDevice.ts
Labels: docs, feature

#1934 fix: add missing argument to xcodebuild shell (destination)
  packages/cli-platform-ios/README.md
  packages/cli-platform-ios/src/commands/buildIOS/buildProject.ts
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
Labels: docs, feature

#1928 feat: add `--target` option
  packages/cli-platform-ios/README.md
  packages/cli-platform-ios/src/commands/buildIOS/buildProject.ts
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
Labels: docs, feature

#1937 feat: add `watchModeCommandParams` to `react-native.config.js`
  docs/platforms.md
  docs/projects.md
  packages/cli-config/src/schema.ts
  packages/cli-platform-android/src/config/__tests__/__snapshots__/getProjectConfig.test.ts.snap
  packages/cli-platform-android/src/config/index.ts
  packages/cli-platform-ios/src/config/__tests__/getProjectConfig.test.ts
  packages/cli-platform-ios/src/config/index.ts
  packages/cli-plugin-metro/src/commands/start/runServer.ts
  packages/cli-plugin-metro/src/commands/start/watchMode.ts
  packages/cli-types/src/android.ts
  packages/cli-types/src/ios.ts
Labels: docs, feature

#1945 chore: improve codebase
  packages/cli-doctor/src/tools/runAutomaticFix.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
Labels: infra

#1941 feat (doctor): add packager healthcheck to report if packager is running correctly
  packages/cli-doctor/package.json
  packages/cli-doctor/src/tools/healthchecks/index.ts
  packages/cli-doctor/src/tools/healthchecks/packager.ts
  packages/cli-doctor/tsconfig.json
  packages/cli-platform-android/src/commands/buildAndroid/index.ts
  packages/cli-platform-android/tsconfig.json
  packages/cli-plugin-metro/src/commands/index.ts
  packages/cli-plugin-metro/src/commands/start/index.ts
  packages/cli-plugin-metro/src/commands/start/startServerInNewWindow.ts
  packages/cli-plugin-metro/src/index.ts
Labels: feature
