Repository react-native-community/cli, pull requests merged in 2023-11, with the labels that each got.

#2148 fix(e2e): correctly link packages
  __e2e__/config.test.ts
  __e2e__/root.test.ts
  jest/helpers.ts
  packages/cli-platform-ios/src/tools/installPods.ts
Labels: bugfix

#2153 feat(ios): sort simulators to get iOS first
  packages/cli-platform-ios/src/tools/__tests__/findMatchingSimulator.test.ts
  packages/cli-platform-ios/src/tools/findMatchingSimulator.ts
Labels: feature

#2145 perf: remove Gradle task check on run-android #2144 (11.x backport)
  packages/cli-platform-android/README.md
  packages/cli-platform-android/src/commands/buildAndroid/index.ts
  packages/cli-platform-android/src/commands/runAndroid/getTaskNames.ts
  packages/cli-platform-android/src/commands/runAndroid/index.ts
  packages/cli-platform-android/src/commands/runAndroid/listAndroidTasks.ts
  packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
Labels: docs

#2160 chore: replace `fs.rmdir` with `fs.rm`
  packages/cli-clean/src/clean.ts
Labels: infra

#2158 fix: remove hardcoded android path
  packages/cli-clean/src/clean.ts
Labels: bugfix

#2157 fix(ci): setup global git user
  .github/workflows/test.yml
Labels: bugfix

#2170 feat: add platform-name option to init for out of tree platforms init
  __e2e__/init.test.ts
  packages/cli/src/commands/init/index.ts
  packages/cli/src/commands/init/init.ts
  packages/cli/src/index.ts
Labels: feature

#2171 fix: platform-name option causing regressions for other commands
  __e2e__/default.test.ts
  packages/cli/src/index.ts
Labels: bugfix

#2172 fix: make sure command is passed
  packages/cli/src/index.ts
Labels: bugfix

#2178 feat(docs): sync `init` docs with current state
  docs/init.md
Labels: docs, feature

#2176 feat(docs): mention running CLI from source
  CONTRIBUTING.md
Labels: docs, feature

#2177 feat: add `--skip-git-init` to opt out git init
  docs/commands.md
  packages/cli/src/commands/init/index.ts
  packages/cli/src/commands/init/init.ts
Labels: docs, feature

#2185 chore(ios): remove deprecated param in `use_native_modules`
  packages/cli-platform-ios/native_modules.rb
Labels: bugfix

#2173 fix(ios): `run-ios` command
  __e2e__/init.test.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-tools/src/__tests__/cacheManager.test.ts
  packages/cli-tools/src/cacheManager.ts
  packages/cli/src/commands/init/init.ts
Labels: bugfix

#2186 feat: mention `doctor` command in issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: docs, feature

#2187 fix: remove error when main activity not found in `AndroidManifest.xml`
  packages/cli-platform-android/src/config/index.ts
Labels: bugfix

#2190 fix: warning in `README.md`
  README.md
Labels: docs, bugfix
