Repository react-native-community/cli, pull requests merged in 2023-02, with the labels that each got.

#1817 chore: update compatibility table
  README.md
Labels: docs, infra

#1811 feat: interactive mode for selecting mode and scheme for iOS
  packages/cli-platform-ios/src/commands/buildIOS/buildProject.ts
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/listIOSDevices.ts
  packages/cli-platform-ios/src/tools/prompts.ts
  packages/cli-platform-ios/src/tools/selectFromInteractiveMode.ts
Labels: feature

#1823 fix: correctly list ios devices and simulators
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/listIOSDevices.ts
  packages/cli-platform-ios/src/tools/__tests__/findMatchingSimulator.test.ts
  packages/cli-platform-ios/src/tools/__tests__/getDevices.test.ts
  packages/cli-platform-ios/src/tools/__tests__/listIOSDevices.test.ts
  packages/cli-platform-ios/src/tools/__tests__/parseIOSDevicesList.test.ts
  packages/cli-platform-ios/src/tools/__tests__/parseXctraceIOSDevicesList.test.ts
  packages/cli-platform-ios/src/tools/findMatchingSimulator.ts
  packages/cli-platform-ios/src/tools/getDevices.ts
  packages/cli-platform-ios/src/tools/listIOSDevices.ts
  packages/cli-platform-ios/src/tools/parseIOSDevicesList.ts
  packages/cli-platform-ios/src/tools/parseXctraceIOSDevicesList.ts
  packages/cli-platform-ios/src/tools/prompts.ts
Labels: bugfix

#1826 feat: add tip to run doctor when build fails
  packages/cli-platform-android/src/commands/buildAndroid/index.ts
  packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
  packages/cli-platform-ios/src/commands/buildIOS/buildProject.ts
  packages/cli-tools/src/index.ts
  packages/cli-tools/src/printRunDoctorTip.ts
Labels: feature

#1822 feat: add --extra-params to run-ios & build-ios command
  docs/commands.md
  packages/cli-platform-android/src/commands/buildAndroid/index.ts
  packages/cli-platform-ios/src/commands/buildIOS/buildProject.ts
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
Labels: docs, feature

#1818 feat: ruby version check for RN CLI Doctor
  packages/cli-doctor/src/tools/envinfo.ts
  packages/cli-doctor/src/tools/healthchecks/index.ts
  packages/cli-doctor/src/tools/healthchecks/ruby.ts
  packages/cli-doctor/src/tools/versionRanges.ts
  packages/cli-doctor/src/types.ts
Labels: command: doctor, feature

#1836 fix: e2e tests
  __e2e__/__snapshots__/config.test.ts.snap
  __e2e__/config.test.ts
  __e2e__/root.test.ts
Labels: bugfix

#1840 docs: make `description` field mandatory
  docs/healthChecks.md
  packages/cli-doctor/src/tools/healthchecks/ruby.ts
  packages/cli-doctor/src/types.ts
Labels: docs

#1843 Breaking: Remove androidMkPath from react-native config
  docs/autolinking.md
  docs/dependencies.md
  docs/platforms.md
  packages/cli-config/src/schema.ts
  packages/cli-platform-android/native_modules.gradle
  packages/cli-platform-android/src/config/index.ts
  packages/cli-types/src/android.ts
Labels: docs

#1841 [10.x] chore(deps): Metro to 0.73.8 (Terser source map fixes)
  package.json
  packages/cli-plugin-metro/package.json
  yarn.lock
Labels: infra

#1830 fix: parsing namespace with single quotes
  packages/cli-platform-android/src/config/__tests__/getAndroidProject.test.ts
  packages/cli-platform-android/src/config/getAndroidProject.ts
Labels: bugfix

#1847 docs: change build badge source
  README.md
Labels: docs
