Repository react-native-community/cli, pull requests merged in 2023-08, with the labels that each got.

#2045 feat: update doctor to reflect Java >= 17
  packages/cli-doctor/src/tools/healthchecks/__tests__/jdk.test.ts
  packages/cli-doctor/src/tools/versionRanges.ts
Labels: feature

#2017 chore: bump `lerna` to `7.1.3`
  lerna.json
  package.json
  yarn.lock
Labels: infra

#2034 chore: upgrade GitHub actions
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: infra

#2026 breaking: remove `--variant` option from `run/build-android` command
  packages/cli-platform-android/README.md
  packages/cli-platform-android/src/commands/buildAndroid/index.ts
  packages/cli-platform-android/src/commands/runAndroid/index.ts
  packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
Labels: docs

#2027 docs(android): remove deprecated `--root` and `--appFolder` options
  packages/cli-platform-android/README.md
Labels: docs

#2041 feat: enable pausing handling keystrokes in watch mode
  packages/cli-plugin-metro/src/commands/start/watchMode.ts
  packages/cli-plugin-metro/src/tools/KeyPressHandler.ts
  packages/cli-tools/src/index.ts
  packages/cli-tools/src/prompt.ts
Labels: feature

#2033 fix: prevent booting already booted simulators
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-platform-ios/src/tools/__tests__/findMatchingSimulator.test.ts
  packages/cli-platform-ios/src/tools/findMatchingSimulator.ts
  packages/cli-platform-ios/src/types.ts
Labels: bugfix

#2021 feat: add invoking CLI's scripts for launching Metro in `run-ios` command
  packages/cli-clean/package.json
  packages/cli-doctor/package.json
  packages/cli-doctor/src/tools/healthchecks/packager.ts
  packages/cli-platform-android/package.json
  packages/cli-platform-android/src/commands/buildAndroid/index.ts
  packages/cli-platform-android/src/commands/runAndroid/index.ts
  packages/cli-platform-ios/src/commands/buildIOS/buildProject.ts
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-plugin-metro/src/commands/index.ts
  packages/cli-plugin-metro/src/commands/start/index.ts
  packages/cli-plugin-metro/src/commands/start/runServer.ts
  packages/cli-plugin-metro/src/index.ts
  packages/cli-server-api/src/statusPageMiddleware.ts
  packages/cli-tools/src/getNextPort.ts
  packages/cli-tools/src/getPidFromPort.ts
  packages/cli-tools/src/handlePortUnavailable.ts
  packages/cli-tools/src/index.ts
  packages/cli-tools/src/isPackagerRunning.ts
  packages/cli-tools/src/launchPackager.bat
  packages/cli-tools/src/launchPackager.command
  packages/cli-tools/src/port.ts
  packages/cli-tools/src/startServerInNewWindow.ts
  packages/cli/package.json
  yarn.lock
Labels: docs, feature

#2056 fix: change request response in `/status` endpoint
  packages/cli-server-api/src/__tests__/statusPageMiddleware.test.ts
  packages/cli-server-api/src/statusPageMiddleware.ts
  packages/cli-tools/src/isPackagerRunning.ts
Labels: bugfix

#2035 docs: add `npx` prefix before `react-native` command
  .github/ISSUE_TEMPLATE/bug_report.md
  CONTRIBUTING.md
  README.md
  docs/commands.md
  docs/healthChecks.md
  docs/init.md
  docs/plugins.md
  docs/projects.md
  packages/cli-clean/README.md
  packages/cli-config/README.md
  packages/cli-config/src/__tests__/__snapshots__/index-test.ts.snap
  packages/cli-config/src/readConfigFromDisk.ts
  packages/cli-doctor/README.md
  packages/cli-doctor/src/tools/healthchecks/packager.ts
  packages/cli-hermes/README.md
  packages/cli-platform-android/README.md
  packages/cli-platform-ios/README.md
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-plugin-metro/README.md
  packages/cli-tools/src/printRunDoctorTip.ts
Labels: docs

#1951 feat: extract android applicationId
  __e2e__/__snapshots__/config.test.ts.snap
  packages/cli-platform-android/src/commands/runAndroid/tryLaunchAppOnDevice.ts
  packages/cli-platform-android/src/config/__fixtures__/files/build.gradle
  packages/cli-platform-android/src/config/__tests__/__snapshots__/getProjectConfig.test.ts.snap
  packages/cli-platform-android/src/config/getAndroidProject.ts
  packages/cli-platform-android/src/config/index.ts
  packages/cli-types/src/android.ts
Labels: feature
