Repository react-native-community/cli, pull requests merged in 2023-07, with the labels that each got.

#1994 docs: sync status with current state of `upgrade` command
  docs/commands.md
Labels: docs

#1995 docs: update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#2000 Update contributing guide with missing step to test local changes
  CONTRIBUTING.md
Labels: docs

#2014 fix(perf): ignore Pods and Hermes files when looking for AndroidManifest
  packages/cli-platform-android/src/config/findManifest.ts
Labels: bugfix

#1998 fix: adjust `doctor` command to work with custom `ios/` folder location
  packages/cli-doctor/src/tools/healthchecks/xcodeEnv.ts
Labels: bugfix

#2018 fix: use `none` as platform for printing upgrading link
  packages/cli-tools/src/releaseChecker/printNewRelease.ts
Labels: bugfix

#1999 breaking: Fix ability to override commands via config
  packages/cli/src/index.ts
Labels: bugfix

#2023 docs: CONTRIBUTING.md typo error
  CONTRIBUTING.md
Labels: docs

#2029 docs: fix link to `profile-hermes` command
  docs/commands.md
Labels: docs

#2025 fix: typo in option description
  packages/cli-platform-ios/README.md
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
Labels: docs, bugfix
