Repository react-native-community/cli, pull requests merged in 2023-12, with the labels that each got.

#2195 fix(android): launching app on simulator with different appId than pa…
  packages/cli-platform-android/src/commands/runAndroid/__tests__/runOnAllDevices.test.ts
  packages/cli-platform-android/src/commands/runAndroid/__tests__/tryLaunchAppOnDevice.test.ts
  packages/cli-platform-android/src/commands/runAndroid/index.ts
  packages/cli-platform-android/src/commands/runAndroid/tryLaunchAppOnDevice.ts
Labels: bugfix

#2200 test: update snapshot for e2e config test
  __e2e__/__snapshots__/config.test.ts.snap
Labels: bugfix

#2197 fix: launchEditor not working for JetBrains IDEs
  packages/cli-tools/src/launchEditor.ts
Labels: bugfix

#2191 feat: add gradlew doctor check permissions
  packages/cli-doctor/src/tools/healthchecks/gradle.ts
  packages/cli-doctor/src/tools/healthchecks/index.ts
Labels: feature

#2204 feat: add manual Cocoapods installation info
  __e2e__/init.test.ts
  packages/cli/src/commands/init/init.ts
  packages/cli/src/commands/init/printRunInstructions.ts
Labels: feature

#2214 feat(ios): show simulator version in prompt
  packages/cli-platform-ios/src/tools/prompts.ts
Labels: feature

#2162 feat(ios): cache last used device
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-platform-ios/src/tools/prompts.ts
  packages/cli-tools/src/cacheManager.ts
Labels: feature

#2215 chore(init): remove error when Git initialisation failed
  packages/cli/src/commands/init/createGitRepository.ts
Labels: infra

#2218 feat: add strict typing for supported platforms
  packages/cli-platform-apple/src/__tests__/pods.test.ts
  packages/cli-platform-apple/src/commands/buildCommand/buildProject.ts
  packages/cli-platform-apple/src/commands/buildCommand/createBuild.ts
  packages/cli-platform-apple/src/commands/buildCommand/simulatorDestinationMap.ts
  packages/cli-platform-apple/src/commands/logCommand/createLog.ts
  packages/cli-platform-apple/src/commands/runCommand/createRun.ts
  packages/cli-platform-apple/src/commands/runCommand/getPlatformInfo.ts
  packages/cli-platform-apple/src/commands/runCommand/runOnDevice.ts
  packages/cli-platform-apple/src/commands/runCommand/runOnSimulator.ts
  packages/cli-platform-apple/src/config/__tests__/findPodfilePath.test.ts
  packages/cli-platform-apple/src/config/findPodfilePath.ts
  packages/cli-platform-apple/src/config/supportedPlatforms.ts
  packages/cli-platform-apple/src/tools/pods.ts
  packages/cli-platform-apple/src/types.ts
Labels: feature

#2225 fix: only run app on booted and available devices
  packages/cli-platform-apple/src/commands/runCommand/createRun.ts
Labels: bugfix

#2224 chore: move devices prompt to `prompts.ts`
  packages/cli-platform-apple/src/commands/logCommand/createLog.ts
  packages/cli-platform-apple/src/tools/prompts.ts
Labels: infra

#2226 feat: convert command options and dependencyConfig into getters
  packages/cli-platform-apple/README.md
  packages/cli-platform-apple/src/commands/buildCommand/buildOptions.ts
  packages/cli-platform-apple/src/commands/logCommand/logOptions.ts
  packages/cli-platform-apple/src/commands/runCommand/runOptions.ts
  packages/cli-platform-apple/src/config/index.ts
  packages/cli-platform-apple/src/index.ts
  packages/cli-platform-ios/src/commands/buildIOS/index.ts
  packages/cli-platform-ios/src/commands/logIOS/index.ts
  packages/cli-platform-ios/src/commands/runIOS/index.ts
  packages/cli-platform-ios/src/config/index.ts
Labels: docs, feature

#2223 feat: warn about multiple podfiles only if provided platform is unsupported
  packages/cli-platform-apple/src/commands/buildCommand/createBuild.ts
  packages/cli-platform-apple/src/commands/buildCommand/getXcodeProjectAndDir.ts
  packages/cli-platform-apple/src/commands/logCommand/createLog.ts
  packages/cli-platform-apple/src/commands/runCommand/createRun.ts
  packages/cli-platform-apple/src/config/findPodfilePath.ts
Labels: feature

#2230 chore: disable flaky tests
  packages/cli/src/tools/__tests__/copyFiles.test.ts
Labels: infra

#2235 chore: disable `editTemplate` test on Node v20
  packages/cli/src/commands/init/__tests__/editTemplate.test.ts
Labels: infra

#2233 feat: fallback to OOT scheme
  packages/cli-platform-apple/src/commands/buildCommand/createBuild.ts
  packages/cli-platform-apple/src/commands/buildCommand/getConfiguration.ts
  packages/cli-platform-apple/src/commands/runCommand/createRun.ts
Labels: feature

#2236 Fix for `run-android` on windows.
  packages/cli-platform-android/src/commands/runAndroid/index.ts
  packages/cli-tools/src/getDefaultUserTerminal.ts
  packages/cli-tools/src/startServerInNewWindow.ts
Labels: bugfix
