Repository react-native-community/cli, pull requests merged in 2024-09, with the labels that each got.

#2475 feat: determine react-native → template from npm registry data
  packages/cli/src/commands/init/__tests__/version.test.ts
  packages/cli/src/commands/init/constants.ts
  packages/cli/src/commands/init/init.ts
  packages/cli/src/commands/init/types.ts
  packages/cli/src/commands/init/version.ts
  packages/cli/src/tools/__tests__/npm-test.ts
  packages/cli/src/tools/npm.ts
Labels: feature

#2394 fix: Correctly display errors in react-native init
  packages/cli/src/commands/init/init.ts
Labels: bugfix

#2500 ci: disable `react-native-macos` test
  __e2e__/init.test.ts
Labels: bugfix

#2504 chore: remove deprecated --npm flag
  __e2e__/init.test.ts
  docs/commands.md
  docs/init.md
  packages/cli/src/commands/init/index.ts
  packages/cli/src/commands/init/init.ts
Labels: command: init, docs

#2503 chore: set npm as default package manager to init
  __e2e__/init.test.ts
  docs/init.md
  packages/cli/src/commands/init/index.ts
  packages/cli/src/commands/init/init.ts
Labels: command: init, docs

#2363 fix: use preferred device in default mode
  packages/cli-platform-apple/src/commands/runCommand/createRun.ts
  packages/cli-platform-apple/src/tools/prompts.ts
Labels: stale, bugfix

#2513 chore: use fast-glob for link-assets and scripts
  package.json
  packages/cli-link-assets/package.json
  packages/cli-link-assets/src/tools/helpers/font/androidFontAssetHelpers.ts
  scripts/build.js
  scripts/linkPackages.js
Labels: bugfix
