Repository react-native-community/cli, pull requests merged in 2024-01, with the labels that each got.

#2234 refactor(cli-platform-apple): move installing and launching app logic to separate function
  packages/cli-platform-apple/src/commands/runCommand/getBuildPath.ts
  packages/cli-platform-apple/src/commands/runCommand/getBuildSettings.ts
  packages/cli-platform-apple/src/commands/runCommand/installApp.ts
  packages/cli-platform-apple/src/commands/runCommand/runOnDevice.ts
  packages/cli-platform-apple/src/commands/runCommand/runOnSimulator.ts
Labels: infra

#2242 fix: regression where run was executing multiple times
  packages/cli-platform-apple/src/commands/runCommand/createRun.ts
Labels: bugfix

#2134 feat: use Yarn v3 with `nodeLinker: node-modules` for new projects
  __e2e__/init.test.ts
  jest/helpers.ts
  packages/cli/src/commands/init/git.ts
  packages/cli/src/commands/init/init.ts
  packages/cli/src/commands/init/template.ts
  packages/cli/src/tools/executeCommand.ts
  packages/cli/src/tools/packageManager.ts
Labels: feature

#2245 fix(ios): properly pass port to `env` in `xcodebuild`
  packages/cli-platform-apple/src/commands/buildCommand/buildProject.ts
Labels: bugfix

#2232 feat: adapt `buildRun` to properly open macOS apps
  packages/cli-platform-apple/src/commands/runCommand/createRun.ts
  packages/cli-platform-apple/src/commands/runCommand/getBuildPath.ts
  packages/cli-platform-apple/src/commands/runCommand/installApp.ts
  packages/cli-platform-apple/src/commands/runCommand/openApp.ts
  packages/cli-platform-apple/src/commands/runCommand/runOnDevice.ts
  packages/cli-platform-apple/src/commands/runCommand/runOnSimulator.ts
Labels: feature

#2252 fix: do not block `run-ios/android` when failed to start packager
  packages/cli-tools/src/startServerInNewWindow.ts
Labels: bugfix

#2250 docs: projects.md to include type information
  docs/projects.md
Labels: docs

#2209 fix: replacing package name in Kotlin template
  packages/cli/src/commands/init/__fixtures__/editTemplate/android/android-java/com/placeholdername/MainActivity.java
  packages/cli/src/commands/init/__fixtures__/editTemplate/android/android-java/com/placeholdername/PlaceholderName.java
  packages/cli/src/commands/init/__fixtures__/editTemplate/android/android-kotlin/com/placeholdername/MainActivity.kt
  packages/cli/src/commands/init/__fixtures__/editTemplate/android/android-kotlin/com/placeholdername/PlaceholderName.kt
  packages/cli/src/commands/init/__fixtures__/editTemplate/android/com/placeholdername/Main.java
  packages/cli/src/commands/init/__fixtures__/editTemplate/android/strings.xml
  packages/cli/src/commands/init/__tests__/__snapshots__/editTemplate.test.ts.snap
  packages/cli/src/commands/init/__tests__/editTemplate.test.ts
  packages/cli/src/commands/init/editTemplate.ts
Labels: bugfix

#2251 fix(cli-platform-apple): properly receive simulators
  packages/cli-platform-apple/src/commands/logCommand/createLog.ts
  packages/cli-platform-apple/src/commands/runCommand/createRun.ts
  packages/cli-platform-apple/src/tools/__tests__/listDevices.test.ts
  packages/cli-platform-apple/src/tools/getSimulators.ts
  packages/cli-platform-apple/src/tools/listDevices.ts
Labels: bugfix

#2100 feat: log files in selected directory and add option to replace them
  __e2e__/init.test.ts
  docs/commands.md
  packages/cli/src/commands/init/errors/DirectoryAlreadyExistsError.ts
  packages/cli/src/commands/init/index.ts
  packages/cli/src/commands/init/init.ts
Labels: docs, feature

#2229 feat: allow overriding commands from `react-native.config.js`
  docs/plugins.md
  packages/cli-config/src/__tests__/__snapshots__/index-test.ts.snap
  packages/cli-config/src/__tests__/index-test.ts
  packages/cli-config/src/loadConfig.ts
Labels: docs, feature

#2263 fix: allow users to specify `--device` without value
  packages/cli-platform-apple/src/commands/runCommand/runOptions.ts
Labels: bugfix

#2264 feat: Deprecate `unstable_reactLegacyComponentNames`
  docs/projects.md
  packages/cli-config/src/schema.ts
  packages/cli-platform-android/native_modules.gradle
  packages/cli-platform-android/src/config/index.ts
  packages/cli-platform-apple/src/config/index.ts
  packages/cli-types/src/android.ts
Labels: docs, feature

#2258 Fix: cleaning metro cache
  packages/cli-clean/package.json
  packages/cli-clean/src/__tests__/clean.test.ts
  packages/cli-clean/src/clean.ts
Labels: bugfix

#2269 fix: launching activity defined with fully qualified name
  packages/cli-platform-android/src/commands/runAndroid/__tests__/tryLaunchAppOnDevice.test.ts
  packages/cli-platform-android/src/commands/runAndroid/tryLaunchAppOnDevice.ts
Labels: bugfix

#2272 chore: remove `cli-plugin-metro` package
  CONTRIBUTING.md
  packages/cli-plugin-metro/README.md
  packages/cli-plugin-metro/package.json
  packages/cli/package.json
  scripts/helpers.js
Labels: docs, infra

#2273 feat(init): add `--yarn-config-options` option
  docs/commands.md
  packages/cli/src/commands/init/index.ts
  packages/cli/src/commands/init/init.ts
  packages/cli/src/commands/init/template.ts
Labels: docs, feature

#2281 chore: remove unused `update-metro.js` script
  scripts/update-metro.js
Labels: infra
