Repository react-native-community/cli, pull requests merged in 2024-06, with the labels that each got.

#2405 chore: upgrade deasync to unblock CI
  yarn.lock
Labels: infra

#2385 chore: upgrade parcel to v2
  .gitignore
  packages/cli-debugger-ui/.babelrc
  packages/cli-debugger-ui/.parcelrc
  packages/cli-debugger-ui/package.json
  packages/cli-debugger-ui/src/ui/index.html
  packages/cli-debugger-ui/src/ui/index.js
  yarn.lock
Labels: infra

#2388 fix: correct derivation of fully specified android launch activities
  packages/cli-platform-android/src/commands/runAndroid/__tests__/tryLaunchAppOnDevice.test.ts
  packages/cli-platform-android/src/commands/runAndroid/tryLaunchAppOnDevice.ts
Labels: platform: android, bugfix, javascript

#2377 chore(run-android): deprecate `--deviceId` in favour of `--device`
  packages/cli-platform-android/README.md
  packages/cli-platform-android/src/commands/runAndroid/index.ts
Labels: docs, infra

#2364 fix(ios): prioritize simulators over devices
  packages/cli-platform-apple/src/commands/runCommand/createRun.ts
Labels: bugfix

#2375 feat(run-ios): allow passing UDID inside `--device` option
  packages/cli-platform-apple/src/commands/runCommand/createRun.ts
  packages/cli-platform-apple/src/commands/runCommand/matchingDevice.ts
  packages/cli-platform-apple/src/commands/runCommand/runOptions.ts
  packages/cli-platform-apple/src/types.ts
Labels: feature

#2411 docs: Remove ram-bundle from README
  docs/commands.md
Labels: docs

#2416 chore: remove specifying `-PreactNativeDebugArchitectures` in Android builds
  packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
Labels: infra

#2417 fix: update react-native version in the template for versions >= 0.75.
  __e2e__/init.test.ts
  packages/cli/src/commands/init/__tests__/editTemplate.test.ts
  packages/cli/src/commands/init/editTemplate.ts
  packages/cli/src/commands/init/init.ts
  packages/cli/src/tools/npm.ts
Labels: bugfix

#2421 fix: only show warning about --template & --version when necessary
  packages/cli/src/commands/init/init.ts
Labels: bugfix

#2426 docs: update init.md
  docs/init.md
Labels: docs

#2414 FIX: ```getCommandOutput``` exec thread
  packages/cli-platform-android/native_modules.gradle
Labels: bugfix

#2412 fix: correctly check Yarn version
  packages/cli/src/commands/init/init.ts
Labels: bugfix

#2424 fix: react-native RC2 fixes
  packages/cli/src/commands/init/init.ts
  packages/cli/src/tools/npm.ts
Labels: bugfix

#2420 feat: add `-i` alias for `--interactive` option
  packages/cli-platform-android/README.md
  packages/cli-platform-android/src/commands/buildAndroid/index.ts
  packages/cli-platform-apple/src/commands/buildCommand/buildOptions.ts
  packages/cli-platform-apple/src/commands/logCommand/logOptions.ts
  packages/cli-platform-ios/README.md
Labels: docs, feature

#2436 fix: issue calling init from 0.75.0-rc.1 release
  packages/cli/src/commands/init/init.ts
Labels: bugfix

#2437 docs: document manual publish instructions
  CONTRIBUTING.md
Labels: docs

#2432 fix: skip if there's no `action` or `category`
  packages/cli-platform-android/src/config/__fixtures__/files/AndroidManifest-className.xml
  packages/cli-platform-android/src/config/getMainActivity.ts
Labels: bugfix

#2433 docs: note that `root` property should use `__dirname`
  docs/autolinking.md
  docs/projects.md
Labels: docs

#2428 chore: bump `envinfo` package
  packages/cli-doctor/package.json
  yarn.lock
Labels: infra

#2429 fix(clean): make sure to delete `node_modules` as last item
  packages/cli-clean/src/clean.ts
Labels: bugfix

#2427 chore: remove fix for react-native@0.75.0-rc.0
  packages/cli/src/commands/init/init.ts
Labels: bugfix

#2438 Update README to reflect current status of the CLI
  README.md
Labels: docs

#2430 fix(doctor): update Android Studio detection path on Windows
  packages/cli-doctor/src/tools/healthchecks/androidStudio.ts
Labels: bugfix
