Repository react-native-community/cli, pull requests merged in 2024-03, with the labels that each got.

#2317 chore: RFC-0759 remove upgrade command
  docs/commands.md
  packages/cli/src/commands/index.ts
  packages/cli/src/commands/upgrade/upgrade.ts
Labels: docs

#2319 fix: align `find-up` package version across packages
  packages/cli/package.json
Labels: bugfix

#2325 fix: pass user-defined health checks to config
  packages/cli-config/src/loadConfig.ts
Labels: bugfix

#2326 docs: fix syntax error in health check docs
  docs/healthChecks.md
Labels: docs, bugfix

#2330 fix: sourceMappingURL were incorrect .ts → .js
  scripts/build.js
Labels: bugfix

#2329 fix: init uses yarn assuming version > 1.x
  __e2e__/init.test.ts
  jest/helpers.ts
  packages/cli-platform-android/src/config/findManifest.ts
  packages/cli/src/commands/init/init.ts
Labels: command: init, bugfix

#2314 chore: specify where to run `npx react-native info` for bug reports
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: docs

#2318 fix: save `.env` files under `node_modules/.generated`
  packages/cli-tools/src/startServerInNewWindow.ts
Labels: bugfix
