Repository react-native-community/cli, pull requests merged in 2024-02, with the labels that each got.

#2296 feat: Add support for C++ TurboModules Autolinking
  docs/autolinking.md
  docs/dependencies.md
  docs/platforms.md
  packages/cli-config/src/schema.ts
  packages/cli-platform-android/native_modules.gradle
  packages/cli-platform-android/src/config/index.ts
  packages/cli-types/src/android.ts
Labels: docs, feature

#2301 fix(12.x): replace `ip` package with default value and `--host` flag
  packages/cli-doctor/package.json
  packages/cli-hermes/README.md
  packages/cli-hermes/package.json
  packages/cli-hermes/src/profileHermes/downloadProfile.ts
  packages/cli-hermes/src/profileHermes/index.ts
  packages/cli-hermes/src/profileHermes/metroBundleOptions.ts
  packages/cli-hermes/src/profileHermes/sourcemapUtils.ts
  yarn.lock
Labels: docs

#2300 docs: update iOS auto-linking docs after adding support for PNPM and workspace setups
  docs/autolinking.md
Labels: docs

#2292 fix: `execa` phantom dependency in cli-tools
  packages/cli-tools/package.json
Labels: bugfix

#2290 docs: update `--tasks` option description
  packages/cli-platform-android/README.md
Labels: docs
