Repository react-native-community/cli, pull requests merged in 2024-04, with the labels that each got.

#2343 feat: add support for `react-native.config.ts`
  __e2e__/config.test.ts
  packages/cli-config/package.json
  packages/cli-config/src/readConfigFromDisk.ts
  yarn.lock
Labels: feature

#2334 feat: RFC-0759: check npm and github for template
  docs/commands.md
  packages/cli/src/commands/init/index.ts
  packages/cli/src/commands/init/init.ts
Labels: docs, feature

#2355 fix: downgrade `ws` package
  packages/cli-server-api/package.json
  yarn.lock
Labels: bugfix

#2358 Fixed cannot start Android emulator version 34.1.20.0
  packages/cli-platform-android/src/commands/runAndroid/tryLaunchEmulator.ts
Labels: bugfix

#2367 fix(init): bump Yarn version on older Yarn versions
  packages/cli/src/commands/init/init.ts
Labels: bugfix
