Repository react-native-community/cli, pull requests merged in 2024-07, with the labels that each got.

#2444 feat: improve error message when cannot find Xcode project
  packages/cli-link-assets/src/linkAssets.ts
  packages/cli-platform-apple/src/commands/buildCommand/getXcodeProjectAndDir.ts
Labels: feature

#2387 feat: Support autolinking C++ only TurboModules on Android
  docs/autolinking.md
  packages/cli-platform-android/native_modules.gradle
  packages/cli-platform-android/src/config/index.ts
  packages/cli-types/src/android.ts
Labels: docs, feature

#2445 fix: show only warnings from Yarn when verbose mode is enabled
  packages/cli/src/commands/init/init.ts
Labels: bugfix

#2440 ci: update release script & add nightly releases
  .github/workflows/nigthly-release.yml
  .github/workflows/release.yml
Labels: bugfix

#2447 ci: install dependencies before releasing nightly version
  .github/workflows/nigthly-release.yml
Labels: bugfix

#2448 docs: fix broken link to Podfile in React Native template
  docs/autolinking.md
Labels: docs

#2458 ci: always print debug log from lerna
  .github/workflows/nigthly-release.yml
Labels: bugfix

#2460 feat: add `--version` option
  packages/cli/src/index.ts
Labels: feature
