Repository react-native-community/cli, pull requests merged in 2025-01, with the labels that each got.

#2578 chore: replace `sudo-prompt` with `@vscode/sudo-prompt`
  packages/cli-tools/package.json
  packages/cli-tools/src/runSudo.ts
  yarn.lock
Labels: infra

#2580 fix: adjust log in install Cocoapods prompt
  packages/cli/src/commands/init/init.ts
Labels: bugfix

#2582 feat: Refresh cli-server-api index page
  packages/cli-server-api/src/index.html
Labels: feature

#2586 test: fix e2e test snapshot
  __e2e__/__snapshots__/config.test.ts.snap
Labels: bugfix

#2585 docs: update compatibility table
  README.md
Labels: docs

#2583 breaking: Remove cli-debugger-ui package
  CONTRIBUTING.md
  README.md
  package.json
  packages/cli-debugger-ui/.parcelrc
  packages/cli-debugger-ui/CHANGELOG.md
  packages/cli-debugger-ui/package.json
  packages/cli-debugger-ui/src/middleware/index.ts
  packages/cli-debugger-ui/src/ui/assets/blue-icon.png
  packages/cli-debugger-ui/src/ui/assets/gray-icon.png
  packages/cli-debugger-ui/src/ui/assets/orange-icon.png
  packages/cli-debugger-ui/src/ui/assets/priority.wav
  packages/cli-debugger-ui/src/ui/debuggerWorker.js
  packages/cli-debugger-ui/src/ui/index.css
  packages/cli-debugger-ui/src/ui/index.html
  packages/cli-debugger-ui/src/ui/index.js
  packages/cli-debugger-ui/tsconfig.json
  packages/cli-server-api/package.json
  packages/cli-server-api/src/devToolsMiddleware.ts
  packages/cli-server-api/src/index.ts
  packages/cli-server-api/src/websocket/createDebuggerProxyEndpoint.ts
  packages/cli-server-api/tsconfig.json
  packages/cli/package.json
  packages/cli/tsconfig.json
  yarn.lock
Labels: docs
