Repository react-native-community/cli, pull requests merged in 2025-02, with the labels that each got.

#2520 fix: Remove hardcoded npm registry url
  packages/cli/src/tools/npm.ts
Labels: stale, bugfix

#2521 refactor: replace strip-ansi with native module
  packages/cli-doctor/package.json
  packages/cli-doctor/src/tools/healthchecks/common.ts
  yarn.lock
Labels: stale

#2597 chore: Link to test setup in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#2598 Update maintainers to reflect current state of things
  CODEOWNERS
  README.md
Labels: docs

#2443 fix(apple): include check if `Podfile` and `Podfile.lock` changed when deciding to install Cocoapods
  packages/cli-config-apple/src/__tests__/pods.test.ts
  packages/cli-config-apple/src/tools/pods.ts
  packages/cli-platform-apple/src/commands/buildCommand/createBuild.ts
  packages/cli-platform-apple/src/commands/runCommand/createRun.ts
  packages/cli-tools/src/cacheManager.ts
Labels: bugfix

#2605 feat: Export `createDevServerMiddleware` from `cli`
  packages/cli/src/index.ts
Labels: feature

#2602 feat: install Cocoapods by default in all projects
  docs/projects.md
  packages/cli-config/src/schema.ts
Labels: docs, feature

#2613 docs: fix numbered lists and spelling in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs
