Repository react-native-community/cli, pull requests merged in 2025-03, with the labels that each got.

#2614 feat: replace ios-deploy with devicectl
  packages/cli-doctor/src/tools/healthchecks/index.ts
  packages/cli-doctor/src/tools/healthchecks/iosDeploy.ts
  packages/cli-platform-apple/src/commands/runCommand/installApp.ts
  packages/cli-platform-apple/src/commands/runCommand/runOnDevice.ts
Labels: feature

#2622 docs: update compatibility table
  README.md
Labels: docs

#2609 fix: remove cocoapods log from `init` command
  packages/cli/src/commands/init/init.ts
Labels: bugfix
